### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by nougad** [erikd/http-proxy#1]
Hi,

I tried to update the dependencies of http-proxy to conduit-0.5. But with my non existing haskell skillz I get stuck. So I want to ask if you maybe can update the dependencies by yourself.

Here my patch:

http://indeedgeek.de/~feitel/tmp/http-proxy.patch

I got two compiling issues I didn't get fixed. But maybe you can need some lines of the patch.

**Comment by erikd** [comment]
This has been working for some time. Cosing.
