### ISSUE TITLE
Can't modify CONNECT requests

### ISSUE THREAD

**Issue by jcpetruzza** [erikd/http-proxy#6]
The case analysis to handle the `CONNECT` request is currently being done before applying `proxyRequestModifier` to the request. This means that one cannot have the proxy prevent certain `CONNECT` requests from succeeding nor fiddle with the host/port where to connect.

Is there a reason behind this?

**Comment by erikd** [comment]
No particular reason. I agree, what you suggest should be possible.

I'll probably get to it in the next couple of days.

**Comment by erikd** [comment]
That was easy. Version 0.1.0.1 on Hackage.

**Comment by jcpetruzza** [comment]
The fix and the upload to hackage are much appreciated, thanks!
