### ISSUE TITLE
Build failure with http-client-0.5 / http-conduit-2.2

### ISSUE THREAD

**Issue by phadej** [erikd/http-proxy#7]
```
Dependency http-client ==0.5.0: using http-client-0.5.0
Dependency http-conduit ==2.2.0: using http-conduit-2.2.0
...
[1 of 2] Compiling Network.HTTP.Proxy.Request ( Network/HTTP/Proxy/Request.hs, dist/dist-sandbox-6636fee0/build/Network/HTTP/Proxy/Request.o )
[2 of 2] Compiling Network.HTTP.Proxy ( Network/HTTP/Proxy.hs, dist/dist-sandbox-6636fee0/build/Network/HTTP/Proxy.o )

Network/HTTP/Proxy.hs:174:19: error:
    Not in scope: ‘HC.checkStatus’
    Neither ‘Network.HTTP.Conduit’ nor ‘Network.HTTP.Client’ exports ‘checkStatus’.
```

**Comment by erikd** [comment]
Thanks. Fixed and new version 0.1.0.2 uploaded to Hackage with upper bounds like:

```
                   , http-client             >= 0.4         && < 0.5
                   , http-conduit            >= 2.1.7       && < 2.2
```

Also intend to release 0.1.0.3 which build with the new versions.

**Comment by erikd** [comment]
Also just uploaded version 0.1.0.3 to Hackage with:

```
                   , http-client             >= 0.5         && < 0.6
                   , http-conduit            >= 2.2         && < 2.3
```

Closing this.

**Comment by phadej** [comment]
The release of `0.1.0.2` was unnecessary and actually a bit harmful. 

Judging from the diff http://hdiff.luite.com/cgit/http-proxy/diff?id=0.1.0.2&id2=0.1.0.1 you started using `parseRequest` only introduced in `http-client-0.4.30`, yet you haven't bumped the lower bound.

I corrected the bounds: https://hackage.haskell.org/package/http-proxy-0.1.0.2/revisions/ for that version. You can do it yourself for your packages, from e.g. https://hackage.haskell.org/package/http-proxy/maintain or https://hackage.haskell.org/package/http-proxy-0.1.0.3/http-proxy.cabal/edit 

Anyway it's bette to make a revision, and new version if only metadata is changed:
- less "similar" versions of packages
- less versions with incorrect bounds (i.e. potentially unbuildable) dependency solver could pick

**Comment by erikd** [comment]
Fair enough! Thanks.
